const questions = [
  { id: 1, topic: 'Physics', text: 'Question 1 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 2, topic: 'Physics', text: 'Question 2 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 3, topic: 'Physics', text: 'Question 3 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 4, topic: 'Physics', text: 'Question 4 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 5, topic: 'Physics', text: 'Question 5 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 6, topic: 'Physics', text: 'Question 6 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 7, topic: 'Physics', text: 'Question 7 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 8, topic: 'Physics', text: 'Question 8 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 9, topic: 'Physics', text: 'Question 9 from NTA 75Q Part 2', answer: 600, type: 'integer', hasDiagram: true },
  { id: 10, topic: 'Physics', text: 'Question 10 from NTA 75Q Part 2', answer: 6, type: 'integer', hasDiagram: true },
  { id: 11, topic: 'Physics', text: 'Question 11 from NTA 75Q Part 2', answer: 240, type: 'integer', hasDiagram: true },
  { id: 12, topic: 'Physics', text: 'Question 12 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 13, topic: 'Physics', text: 'Question 13 from NTA 75Q Part 2', answer: 2, type: 'integer', hasDiagram: true },
  { id: 14, topic: 'Physics', text: 'Question 14 from NTA 75Q Part 2', answer: 15, type: 'integer', hasDiagram: true },
  { id: 15, topic: 'Physics', text: 'Question 15 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 16, topic: 'Physics', text: 'Question 16 from NTA 75Q Part 2', answer: 44, type: 'integer', hasDiagram: true },
  { id: 17, topic: 'Physics', text: 'Question 17 from NTA 75Q Part 2', answer: 27, type: 'integer', hasDiagram: true },
  { id: 18, topic: 'Physics', text: 'Question 18 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 19, topic: 'Physics', text: 'Question 19 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 20, topic: 'Physics', text: 'Question 20 from NTA 75Q Part 2', answer: 2, type: 'integer', hasDiagram: true },
  { id: 21, topic: 'Physics', text: 'Question 21 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 22, topic: 'Physics', text: 'Question 22 from NTA 75Q Part 2', answer: 1, type: 'integer', hasDiagram: true },
  { id: 23, topic: 'Physics', text: 'Question 23 from NTA 75Q Part 2', answer: 1, type: 'integer', hasDiagram: true },
  { id: 24, topic: 'Physics', text: 'Question 24 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 25, topic: 'Physics', text: 'Question 25 from NTA 75Q Part 2', answer: 25, type: 'integer', hasDiagram: true },
  { id: 26, topic: 'Physics', text: 'Question 26 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 27, topic: 'Physics', text: 'Question 27 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 28, topic: 'Physics', text: 'Question 28 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 29, topic: 'Physics', text: 'Question 29 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 30, topic: 'Physics', text: 'Question 30 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 31, topic: 'Physics', text: 'Question 31 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 32, topic: 'Physics', text: 'Question 32 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 33, topic: 'Physics', text: 'Question 33 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 34, topic: 'Physics', text: 'Question 34 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 35, topic: 'Physics', text: 'Question 35 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 36, topic: 'Physics', text: 'Question 36 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 37, topic: 'Physics', text: 'Question 37 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 38, topic: 'Physics', text: 'Question 38 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 39, topic: 'Physics', text: 'Question 39 from NTA 75Q Part 2', answer: 5, type: 'integer', hasDiagram: true },
  { id: 40, topic: 'Physics', text: 'Question 40 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 41, topic: 'Physics', text: 'Question 41 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 42, topic: 'Physics', text: 'Question 42 from NTA 75Q Part 2', answer: 250, type: 'integer', hasDiagram: true },
  { id: 43, topic: 'Physics', text: 'Question 43 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 44, topic: 'Physics', text: 'Question 44 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 45, topic: 'Physics', text: 'Question 45 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 46, topic: 'Physics', text: 'Question 46 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 47, topic: 'Physics', text: 'Question 47 from NTA 75Q Part 2', answer: 2, type: 'integer', hasDiagram: true },
  { id: 48, topic: 'Physics', text: 'Question 48 from NTA 75Q Part 2', answer: 6000, type: 'integer', hasDiagram: true },
  { id: 49, topic: 'Physics', text: 'Question 49 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 50, topic: 'Physics', text: 'Question 50 from NTA 75Q Part 2', answer: 30, type: 'integer', hasDiagram: true },
  { id: 51, topic: 'Physics', text: 'Question 51 from NTA 75Q Part 2', answer: 500, type: 'integer', hasDiagram: true },
  { id: 52, topic: 'Physics', text: 'Question 52 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 53, topic: 'Physics', text: 'Question 53 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 54, topic: 'Physics', text: 'Question 54 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 55, topic: 'Physics', text: 'Question 55 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 56, topic: 'Physics', text: 'Question 56 from NTA 75Q Part 2', answer: 40, type: 'integer', hasDiagram: true },
  { id: 57, topic: 'Physics', text: 'Question 57 from NTA 75Q Part 2', answer: 33, type: 'integer', hasDiagram: true },
  { id: 58, topic: 'Physics', text: 'Question 58 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 59, topic: 'Physics', text: 'Question 59 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 60, topic: 'Physics', text: 'Question 60 from NTA 75Q Part 2', answer: 288, type: 'integer', hasDiagram: true },
  { id: 61, topic: 'Physics', text: 'Question 61 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 62, topic: 'Physics', text: 'Question 62 from NTA 75Q Part 2', answer: 68, type: 'integer', hasDiagram: true },
  { id: 63, topic: 'Physics', text: 'Question 63 from NTA 75Q Part 2', answer: 3, type: 'integer', hasDiagram: true },
  { id: 64, topic: 'Physics', text: 'Question 64 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 65, topic: 'Physics', text: 'Question 65 from NTA 75Q Part 2', answer: 240, type: 'integer', hasDiagram: true },
  { id: 66, topic: 'Physics', text: 'Question 66 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 67, topic: 'Physics', text: 'Question 67 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 68, topic: 'Physics', text: 'Question 68 from NTA 75Q Part 2', answer: 60, type: 'integer', hasDiagram: true },
  { id: 69, topic: 'Physics', text: 'Question 69 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 70, topic: 'Physics', text: 'Question 70 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 71, topic: 'Physics', text: 'Question 71 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 72, topic: 'Physics', text: 'Question 72 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 73, topic: 'Physics', text: 'Question 73 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 74, topic: 'Physics', text: 'Question 74 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 75, topic: 'Physics', text: 'Question 75 from NTA 75Q Part 2', options: ['(1)', '(2)', '(3)', '(4)'], answer: 3, type: 'mcq', hasDiagram: true }
];

const imageMapping = {"1": "page10_img2.jpeg", "2": "page10_img3.jpeg", "3": "page10_img4.jpeg", "4": "page10_img5.jpeg", "5": "page10_img6.jpeg", "6": "page10_img7.jpeg", "7": "page10_img8.jpeg", "8": "page10_img9.jpeg", "9": "page11_img2.jpeg", "10": "page11_img3.jpeg", "11": "page11_img4.jpeg", "12": "page11_img5.jpeg", "13": "page11_img6.jpeg", "14": "page11_img7.jpeg", "15": "page12_img2.jpeg", "16": "page12_img3.jpeg", "17": "page12_img4.jpeg", "18": "page12_img5.jpeg", "19": "page12_img6.jpeg", "20": "page12_img7.jpeg", "21": "page13_img2.jpeg", "22": "page13_img3.jpeg", "23": "page13_img4.jpeg", "24": "page13_img5.jpeg", "25": "page2_img2.jpeg", "26": "page2_img3.jpeg", "27": "page2_img4.jpeg", "28": "page2_img5.jpeg", "29": "page2_img6.jpeg", "30": "page2_img7.jpeg", "31": "page2_img8.jpeg", "32": "page2_img9.jpeg", "33": "page3_img2.jpeg", "34": "page3_img3.jpeg", "35": "page3_img4.jpeg", "36": "page3_img5.jpeg", "37": "page3_img6.jpeg", "38": "page3_img7.jpeg", "39": "page3_img8.jpeg", "40": "page4_img2.jpeg", "41": "page4_img3.jpeg", "42": "page4_img4.jpeg", "43": "page4_img5.jpeg", "44": "page4_img6.jpeg", "45": "page5_img2.jpeg", "46": "page5_img3.jpeg", "47": "page5_img4.jpeg", "48": "page5_img5.jpeg", "49": "page5_img6.jpeg", "50": "page5_img7.jpeg", "51": "page5_img8.jpeg", "52": "page6_img2.jpeg", "53": "page6_img3.jpeg", "54": "page6_img4.jpeg", "55": "page6_img5.jpeg", "56": "page6_img6.jpeg", "57": "page6_img7.jpeg", "58": "page6_img8.jpeg", "59": "page7_img2.jpeg", "60": "page7_img3.jpeg", "61": "page7_img4.jpeg", "62": "page7_img5.jpeg", "63": "page7_img6.jpeg", "64": "page7_img7.jpeg", "65": "page8_img2.jpeg", "66": "page8_img3.jpeg", "67": "page8_img4.jpeg", "68": "page8_img5.jpeg", "69": "page8_img6.jpeg", "70": "page8_img7.jpeg", "71": "page8_img8.jpeg", "72": "page9_img2.jpeg", "73": "page9_img3.jpeg", "74": "page9_img4.jpeg", "75": "page9_img5.jpeg"};