const questions = [
  { id: 1, topic: 'U&D, ERRORS & VECTORS', text: 'Keeping the significant figures in view, the sum of the physical quantities 52.01m, 153.2 m and 0.123 m is :', options: ['205 m', '205.333 m', '205.33 m', '205.3 m'], answer: 4, type: 'mcq' },
  { id: 2, topic: 'U&D, ERRORS & VECTORS', text: 'If ε, E and t represent the free space permittivity, electric field and time respectively, then the unit of εE/t will be :', options: ['Am', 'Am²', 'A/m²', 'A/m'], answer: 3, type: 'mcq' },
  { id: 3, topic: 'U&D, ERRORS & VECTORS', text: 'Four persons measure the length of a rod as 20.00 cm, 19.75 cm, 17.01 cm and 18.25 cm. The relative error in the measurement of average length of the rod is :', options: ['0.24', '0.18', '0.06', '0.08'], answer: 3, type: 'mcq' },
  { id: 4, topic: 'U&D, ERRORS & VECTORS', text: 'In a screw gauge, the zero of the circular scale lies 3 divisions above the horizontal pitch line when their metallic studs are brought in contact. If pitch scale reading is 1 mm and the circular scale reading is 51 then the correct thickness is ___ mm. [Assume least count is 0.01 mm]', options: ['1.50', '1.48', '1.54', '1.51'], answer: 3, type: 'mcq' },
  { id: 5, topic: 'U&D, ERRORS & VECTORS', text: 'A ball of radius r and density ρ dropped through a viscous liquid of density σ and viscosity η attains its terminal velocity at time t, given by t = A p^a r^b η^c σ^d. The value of (b+c)/(a+d) is ___.', answer: 1, type: 'integer' },
  { id: 6, topic: 'U&D, ERRORS & VECTORS', text: 'When both jaws of vernier callipers touch each other, zero mark of the vernier scale is right to zero mark of main scale, 4th mark on vernier scale coincides with certain mark on the main scale. Measured length of cylinder is ___ mm. (Least count = 0.1 mm)', options: ['15.4', '15.1', '15.5', '15.9'], answer: 2, type: 'mcq' },
  { id: 7, topic: 'U&D, ERRORS & VECTORS', text: 'The time period of a simple harmonic oscillator is T = 2π√(k/m). Percentage error in determination of spring constant (k) is ___ %.', options: ['3.43', '3.35', '7.60', '4.76'], answer: 4, type: 'mcq' },
  { id: 8, topic: 'KINEMATICS', text: 'A river of width 200 m is flowing from west to east with a speed of 18 km/h. A boat, moving with speed of 36 km/h in still water, is made to travel one-round trip. Minimum time taken and displacement along the river bank are ___ and ___ respectively.', options: ['20 s and 100 m', '40 s and 0 m', '40 s and 200 m', '40 s and 100 m'], answer: 3, type: 'mcq' },
  { id: 9, topic: 'KINEMATICS', text: 'A paratrooper jumps from an aeroplane and opens a parachute after 2 s of free fall and starts deaccelerating with 3 m/s². The initial height of the aeroplane is ___ m. (g = 10 m/s²)', options: ['62.5', '92.5', '20', '82.5'], answer: 2, type: 'mcq' },
  { id: 10, topic: 'KINEMATICS', text: 'A boy thrown a ball into air at 45° from horizontal to land on roof of height H. If the ball attains maximum height in 2 s and lands on the building in 3 s, value of H is ___ m.', options: ['20', '10', '25', '15'], answer: 4, type: 'mcq' },
  { id: 11, topic: 'KINEMATICS', text: 'Water drops fall from a tap on the floor, 5 m below. The height at which the fourth drop will be from ground, at the instant when the first drop strikes the ground is ___ m.', options: ['2.5', '4.0', '3.2', '3.8'], answer: 3, type: 'mcq' },
  { id: 12, topic: 'KINEMATICS', text: 'A particle starts moving from time t = 0 and its coordinate is given as x(t) = 4t³ - 3t. Choose the correct answer from the options given below :', options: ['A,C,D only', 'A,B,C only', 'C,E only', 'A,C only'], answer: 2, type: 'mcq' },
  { id: 13, topic: 'LAWS OF MOTION', text: 'In the given figure the blocks A, B and C weigh 4 kg, 6 kg and 8 kg respectively. The co-efficient of sliding friction between any two surfaces is 0.5. The force F required to slide the block C with constant speed is ___ N.', answer: 210, type: 'integer', hasDiagram: true },
  { id: 14, topic: 'LAWS OF MOTION', text: 'A flexible chain of mass m hangs between two fixed points. The inclination of the chain with the horizontal at the two points of support is 30°. The tension of the chain at the lowest point is ___.', options: ['(√3/2)mg', '(1/2)mg', 'mg', '(√3)mg'], answer: 1, type: 'mcq' },
  { id: 15, topic: 'LAWS OF MOTION', text: 'A small block of mass m slides down from the top of a frictionless inclined surface, while the inclined plane is moving towards left with constant acceleration a₀. The time it takes to reach the lowest point is ___.', options: ['Formula 1', 'Formula 2', 'Formula 3', 'Formula 4'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 16, topic: 'WEP & CIRCULAR MOTION', text: 'Potential energy (V) versus distance (x) is given by the graph, Rank various regions as per the magnitudes of the force (F) acting on a particle from high to low.', options: ['F_BC > F_CD > F_DE > F_AB', 'F_CD > F_AB > F_BC > F_DE', 'F_CD > F_DE > F_AB > F_BC', 'F_BC > F_AB > F_DE > F_CD'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 17, topic: 'WEP & CIRCULAR MOTION', text: 'In vertical circular motion, if tension is zero at an angle 30° shown in figure, the velocity at the bottom point (A) is ___', options: ['√5gr', '(√7/2)gr', '√4gr', '(√5/2)gr'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 18, topic: 'COM & COLLISION', text: 'A small bob A of mass m hits bob B elastically. If bob B just manages to complete the circular path of radius R, then radius R is ___ m.', options: ['3/5', '1/5', '(2+√3)/5', '(2-√3)/5'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 19, topic: 'COM & COLLISION', text: 'A body of mass 14 kg initially at rest explodes into three fragments (2 : 2 : 3). Two equal masses fly off perpendicular at 18 m/s. Velocity of heavier fragment is ___ m/s.', options: ['10√2', '12√2', '12', '24√2'], answer: 2, type: 'mcq' },
  { id: 20, topic: 'ROTATION', text: 'A uniform rod of mass m and length l suspended by two identical strings. Tension in one string immediately after the other is cut, is ___', options: ['mg/2', 'mg/4', 'mg/3', 'mg'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 21, topic: 'ROTATION', text: 'The pulley shown in figure is made using a thin rim and two rods. The magnitudes of the acceleration experienced by the blocks is ___', options: ['Formula 1', 'Formula 2', 'Formula 3', 'Formula 4'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 22, topic: 'ROTATION', text: 'A uniform bar of length 12 cm and mass 20 m lies on a table. Two point masses m and 2 m strike the bar and get stuck. The ratio of v and ω is :', answer: 1, type: 'integer' },
  { id: 23, topic: 'ROTATION', text: 'A uniform circular disc has shaded regions cut out. The moment of inertia of the remainder about axis A is (x/256) Mr². The value of x is ___.', answer: 109, type: 'integer', hasDiagram: true },
  { id: 24, topic: 'ROTATION', text: 'Two masses are suspended from ends of a light string over a heavy pulley. Rotational inertia of the pulley is ___ kg.m².', options: ['9.5 x 10^-3', '4.75 x 10^-3', '1.86 x 10^-2', '8.3 x 10^-3'], answer: 1, type: 'mcq' },
  { id: 25, topic: 'ROTATION', text: 'A thin uniform rod (X) falls from a vertical position. The angular velocity of this rod when it hits the table top, is ___', options: ['√(3g/2L)', '√(3g/L)', '√(1g/2L)', '√(3g/L)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 26, topic: 'ROTATION', text: 'Two circular discs joined at centres by a rod. Angular acceleration of the discs about axis AB is ___ rad/s².', options: ['22', '11', '100', '27'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 27, topic: 'GRAVITATION', text: 'Initially a satellite of 100 kg is in orbit of 1.5R_E. Energy needed to move it to orbit of 3R_E is α x 10^8 J. The value of α is ___', options: ['150', '500', '100', '1000'], answer: 4, type: 'mcq' },
  { id: 28, topic: 'GRAVITATION', text: 'Net gravitational force at centre of square with masses M, 2M, 3M, 4M. Ratio F_1/F_2 is α/√5. The value of α is ___.', options: ['1', '3', '2', '2√5'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 29, topic: 'PROPERTIES OF SOLIDS', text: 'Two wires A and B are stretched by same magnitude. Ratio of Young\'s modulus of A to B is x : 3. The value of x is ___.', options: ['1', '2', '3', '4'], answer: 4, type: 'mcq' },
  { id: 30, topic: 'FLUID MECHANICS', text: 'Water flows through a horizontal tube. Difference in height is 5 cm. Rate of flow is ___ cm³/s.', options: ['200/√3', '200√6', '200√3', '100√3'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 31, topic: 'FLUID MECHANICS', text: 'Capillary tube height changes if inner radius, density and surface tension decrease by 1 % each. Height will change by ___ %.', options: ['-1', '+3', '-3', '+1'], answer: 4, type: 'mcq' },
  { id: 32, topic: 'FLUID MECHANICS', text: 'Air bubble volume 2.9 cm³ rises from 5 m deep. Volume at surface is ___ cm³.', options: ['4.2', '3.0', '2.0', '4.5'], answer: 4, type: 'mcq' },
  { id: 33, topic: 'SHM', text: 'Kinetic energy of simple harmonic oscillator oscillates with 176 rad/s. Frequency of oscillator is ___ Hz.', options: ['14', '28', '88', '176'], answer: 1, type: 'mcq' },
  { id: 34, topic: 'SHM', text: 'Cylindrical block floating in liquid. Period of oscillation is ___.', options: ['2π√(M/ρAg)', 'π√(2M/ρAg)', 'π√(ρA/Mg)', '2π√(ρA/Mg)'], answer: 1, type: 'mcq' },
  { id: 35, topic: 'SHM', text: 'Spring of force constant 15 N/m cut into pieces (ratio 1:3). Force constant of smaller piece is ___ N/m', options: ['15', '60', '20', '45'], answer: 3, type: 'mcq' },
  { id: 36, topic: 'THERMAL PROPERTIES', text: 'Geyser heats water 5.0 litres/min from 27°C to 87°C. Rate of consumption of gas is ___ g/s.', options: ['2.1', '0.42', '4.2', '0.21'], answer: 3, type: 'mcq' },
  { id: 37, topic: 'THERMAL PROPERTIES', text: 'Aluminium and steel rods length 120 cm at 30°C. Length of composite rod at 100°C is ___ cm.', options: ['120.20', '120.03', '120.15', '120.06'], answer: 2, type: 'mcq' },
  { id: 38, topic: 'THERMAL PROPERTIES', text: 'Rods x and y joined. Thermal conductivity of x is 3 times y. Temperature at junction B and E are:', options: ['89 °C and 73 °C', '80 °C and 60 °C', '80 °C and 70 °C', '60 °C and 45 °C'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 39, topic: 'THERMAL PROPERTIES', text: 'Inelastic collision of two spheres. Rise in temperature is ___ °C.', options: ['1.75', '1.15', '1.44', '1.95'], answer: 2, type: 'mcq' },
  { id: 40, topic: 'THERMAL PROPERTIES', text: 'Brass wire tension increase to 1.4T. Temperature to which wire has to be cooled is ___ °C', options: ['-86', '-65', '-71', '-80'], answer: 2, type: 'mcq' },
  { id: 41, topic: 'KTG & THERMODYNAMICS', text: 'Cylindrical tube AB rotated in horizontal plane. Pressure relation between A and B is:', options: ['P_B = P_A exp(Mω²l² / 2RT)', 'P_B = P_A', 'P_B = P_A exp(Mω²l² / 3RT)', 'P_B = P_A exp(Mω²l² / RT)'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 42, topic: 'KTG & THERMODYNAMICS', text: 'One mole of helium gas heated by 126 J. Temperature rises by 4 °C. Piston moves ___ cm.', options: ['14.5', '15.5', '1.55', '1.45'], answer: 3, type: 'mcq' },
  { id: 43, topic: 'KTG & THERMODYNAMICS', text: 'Water heated from 4°C to 20°C. Increase in internal energy is ___ J.', options: ['315826.2', '234699.2', '258700.8', '268799.2'], answer: 4, type: 'mcq' },
  { id: 44, topic: 'KTG & THERMODYNAMICS', text: 'Work done in the closed path in p-V diagram is ___', options: ['1/a', '1/(2a)', '1/(3a)', '1/(3a)'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 45, topic: 'KTG & THERMODYNAMICS', text: 'Mean free path of molecule at 41°C and 1.38 x 10^5 Pa is ___ m.', options: ['2√2 x 10^-10', '10√2 x 10^-8', '2√2 x 10^-8', '2 x 10^-8'], answer: 3, type: 'mcq' },
  { id: 46, topic: 'WAVE MOTION', text: 'Two strings joined. Ratio of travel times t_1/t_2 to reach joint is :', options: ['1.08', '1.67', '1.90', '1.18'], answer: 4, type: 'mcq' },
  { id: 47, topic: 'WAVE MOTION', text: 'Two loudspeakers separated by 10 m. Frequency of input signal is ___ Hz.', answer: 600, type: 'integer', hasDiagram: true },
  { id: 48, topic: 'WAVE MOTION', text: 'Fifth harmonic of closed pipe in unison with first harmonic of open pipe. Ratio of lengths is 5/x. Value of x is', options: ['4', '2', '1', '3'], answer: 2, type: 'mcq' },
  { id: 49, topic: 'WAVE MOTION', text: 'Speed of longitudinal wave in metallic bar changes when density and Young\'s modulus increase. New speed is ___ m/s.', options: ['399', '398', '402', '401'], answer: 4, type: 'mcq' },
  { id: 50, topic: 'WAVE MOTION', text: 'Original frequency of tuning fork B is 380 Hz. Beat frequency reduced when wax added to A. Frequency of A is ___ Hz.', answer: 384, type: 'integer' },
  { id: 51, topic: 'ELECTROSTATICS', text: 'Two identical metallic spheres of radius R. Minimum value of u so they just touch each other is :', options: ['Formula 1', 'Formula 2', 'Formula 3', 'Formula 4'], answer: 1, type: 'mcq' },
  { id: 52, topic: 'ELECTROSTATICS', text: 'Charges 2q and q on vertex and face of cube. Electric flux passing through the cube is :', options: ['3q/ε₀', 'q/ε₀', '3q/2ε₀', '3q/4ε₀'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 53, topic: 'ELECTROSTATICS', text: 'Two shorts dipoles A and B. Electric field at point P equi-distant from centres is ___ N/C.', options: ['Formula 1', 'Formula 2', 'Formula 3', 'Formula 4'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 54, topic: 'ELECTROSTATICS', text: 'Charges 7μC and -2 μC in external field E = A/r^2. Electrostatic energy is ___ J.', options: ['1.4', '49.3', '-90.7', '24.3'], answer: 3, type: 'mcq' },
  { id: 55, topic: 'ELECTROSTATICS', text: 'Potential V = ar³ + b in charged spherical region. Total charge in sphere of unit radius is α x πε₀. Value of α is', options: ['-12', '-9', '-6', '-8'], answer: 1, type: 'mcq' },
  { id: 56, topic: 'ELECTROSTATICS', text: 'Three co-centric conducting spherical shells. Potential of spheres A, B and C respectively are:', options: ['Formula 1', 'Formula 2', 'Formula 3', 'Formula 4'], answer: 3, type: 'mcq' },
  { id: 57, topic: 'ELECTROSTATICS', text: 'Force between point charge q = 1 μC and wire of charge Q = 24 μC is ___ N.', answer: 8, type: 'integer', hasDiagram: true },
  { id: 58, topic: 'CAPACITORS', text: 'Parallel-plate capacitor filled with three dielectric slabs K1=2, K2=3, K3=5. Value of n is ___.', answer: 8, type: 'integer', hasDiagram: true },
  { id: 59, topic: 'CAPACITORS', text: 'Capacitor draws 25% more charge when mica sheet of 2 mm is introduced. Dielectric constant is ___', options: ['2.5', '1.5', '2.0', '1.0'], answer: 2, type: 'mcq' },
  { id: 60, topic: 'CAPACITORS', text: 'Three parallel plate capacitors with different dielectric arrangements. Which is true? (k1 > k2)', options: ['C_B > C_C > C_A', 'C_C > C_A > C_B', 'C_C > C_B > C_A', 'C_A > C_C > C_B'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 61, topic: 'CAPACITORS', text: 'Identify correct statements about capacitors and dielectrics.', options: ['A, B and C only', 'C and D only', 'A, C and D only', 'B and D only'], answer: 3, type: 'mcq' },
  { id: 62, topic: 'CURRENT ELECTRICITY', text: 'Percentage efficiency of transmission line delivering 1 kW at 250 V through 2 Ω resistance is ___', options: ['96.9', '100', '86.5', '92.5'], answer: 1, type: 'mcq' },
  { id: 63, topic: 'CURRENT ELECTRICITY', text: 'Mobility of electrons in cylindrical conductor is α x 10^-3 m²/V.s. Value of α is :', answer: 1, type: 'integer' },
  { id: 64, topic: 'CURRENT ELECTRICITY', text: 'Equivalent resistance of regular hexagon between opposite corners is', options: ['4/5 r', '3/4 r', '5/8 r', '3/5 r'], answer: 1, type: 'mcq' },
  { id: 65, topic: 'CURRENT ELECTRICITY', text: 'Meter bridge null point shifts by 10 cm when x is in parallel to 3 Ω. Value of x is ___ Ω.', answer: 6, type: 'integer' },
  { id: 66, topic: 'CURRENT ELECTRICITY', text: 'Internal resistance of cell from potentiometer balance lengths with different shunts is ___ Ω.', options: ['3', '12', '4', '6'], answer: 2, type: 'mcq' },
  { id: 67, topic: 'CURRENT ELECTRICITY', text: 'Equivalent resistance between A and B is x/5 Ω. Value of x is ___.', answer: 21, type: 'integer', hasDiagram: true },
  { id: 68, topic: 'CURRENT ELECTRICITY', text: 'Potential difference (Va - Vb) in Wheatstone bridge when R3 increases by 10% is ___ V.', options: ['1.05', '0', '0.95', '2'], answer: 3, type: 'mcq', hasDiagram: true },
  { id: 69, topic: 'MOVING CHARGES & MEC', text: 'Work done in moving magnet from stable to unstable position is α x 10^-3 J. Value of α is ___.', answer: 64, type: 'integer' },
  { id: 70, topic: 'MOVING CHARGES & MEC', text: 'Net magnetic field at centre O of two circular loops P and Q is :', options: ['Formula 1', 'Formula 2', 'Formula 3', 'Formula 4'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 71, topic: 'MOVING CHARGES & MEC', text: 'Force experienced by 15 cm length of wire Q is ___', options: ['Formula 1', 'Formula 2', 'Formula 3', 'Formula 4'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 72, topic: 'ELECTROMAGNETIC INDUCTION', text: 'Average thermal energy dissipated in circular loop in magnetic field B = sin(100 π t) is ___ J.', options: ['π/2', 'π', '2π', 'π²'], answer: 2, type: 'mcq' },
  { id: 73, topic: 'ELECTROMAGNETIC INDUCTION', text: 'Force needed to move rod towards right with constant speed is ___ N.', options: ['7.5 x 10^-2', '5.7 x 10^-2', '5.7 x 10^-3', '7.5 x 10^-3'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 74, topic: 'ELECTROMAGNETIC INDUCTION', text: 'Induced current in C2 is clockwise when coils move as:', options: ['C1, C3 away', 'C1 towards, C3 away', 'C1 away, C3 towards', 'C1, C3 towards'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 75, topic: 'ELECTROMAGNETIC INDUCTION', text: 'Energy density in inductor reaches 1/e² of max value. Value of α is ___ (assuming missing length parameter).', answer: 20, type: 'integer' },
  { id: 76, topic: 'ELECTROMAGNETIC INDUCTION', text: 'Radius of loop rotating in magnetic field with induced EMF 15.4 mV is ___ mm.', answer: 14, type: 'integer' },
  { id: 77, topic: 'ELECTROMAGNETIC INDUCTION', text: 'Maximum induced EMF in simple pendulum in magnetic field is ___ mV.', answer: 100, type: 'integer' },
  { id: 78, topic: 'ELECTROMAGNETIC INDUCTION', text: 'R.m.s current in loop when solenoid current is 10 sin(ωt) is α/√2 μA. Value of α is', options: ['197', '280', '80', '100'], answer: 1, type: 'mcq' },
  { id: 79, topic: 'ALTERNATING CURRENT', text: 'Time t at which 25% of energy is transferred to inductor is ___ s.', options: ['π√LC / 3', 'π√LC / 2', 'π√LC / 6', 'π√LC / 2'], answer: 2, type: 'mcq' },
  { id: 80, topic: 'ALTERNATING CURRENT', text: 'Capacitance of capacitor used in LCR circuit for max current 50 mA is ___ μF.', answer: 50, type: 'integer', hasDiagram: true },
  { id: 81, topic: 'ALTERNATING CURRENT', text: 'R.m.s current for current i = i₀(t/T) from t=0 to T is', options: ['i₀/√2', 'i₀/√6', 'i₀', 'i₀/√3'], answer: 4, type: 'mcq' },
  { id: 82, topic: 'WAVE OPTICS', text: 'Central fringe shift in double slit experiment. Value of t is ___ cm.', options: ['8 x 10^-4', '5.6 x 10^-4', '6.0 x 10^-3', '5.0 x 10^-3'], answer: 1, type: 'mcq' },
  { id: 83, topic: 'WAVE OPTICS', text: 'Reflected beam is polarized at particular angle. Refractive angle is ___', options: ['39.6°', '42.6°', '32.3°', '36.3°'], answer: 2, type: 'mcq' },
  { id: 84, topic: 'WAVE OPTICS', text: 'Intensity on screen in front of one slit in YDSE is ___ (each slit intensity I₀).', options: ['2I₀', 'I₀', 'I₀/2', '4I₀'], answer: 2, type: 'mcq' },
  { id: 85, topic: 'EM WAVES', text: 'Ratio of maximum conducting current density to displacement current density is ___.', answer: 1800, type: 'integer' },
  { id: 86, topic: 'EM WAVES', text: 'Dielectric constant of medium for given electromagnetic wave electric field is', answer: 4, type: 'integer' },
  { id: 87, topic: 'EM WAVES', text: 'Amplitude of magnetic field for laser beam intensity 4.0 x 10^14 W/m² is ___ T.', options: ['2.0', '5.5', '18.3', '1.83'], answer: 4, type: 'mcq' },
  { id: 88, topic: 'EM WAVES', text: 'Average power of EM wave is 1/α W/m². Value of α is ___.', answer: 2, type: 'integer' },
  { id: 89, topic: 'RAY OPTICS', text: 'Focal length of second lens to expand collimated beam is ___ mm.', answer: 280, type: 'integer' },
  { id: 90, topic: 'RAY OPTICS', text: 'Magnification produced by microscope for normal adjustment is ___.', answer: 100, type: 'integer' },
  { id: 91, topic: 'RAY OPTICS', text: 'Incident ray parallel to base, emergent ray grazes second surface. Angle θ of prism is.', options: ['60°', '90°', '75°', '45°'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 92, topic: 'RAY OPTICS', text: 'Combination of convex and concave lens. Value of |m_1/m_2| is ___ (Dropped in official key).', answer: 'Dropped', type: 'integer' },
  { id: 93, topic: 'RAY OPTICS', text: 'Angle of second prism to produce dispersion without deviation is ___', options: ['4.5°', '4°', '6°', '5°'], answer: 3, type: 'mcq' },
  { id: 94, topic: 'RAY OPTICS', text: 'Prism coated with thin film. Incident angle for total internal reflection at back surface must be', options: ['between 15° and 20°', '> 25°', '15°', '< 15°'], answer: '1,2,4', type: 'mcq' },
  { id: 95, topic: 'RAY OPTICS', text: 'Focal length of lens for equal sized images at 8 cm and 24 cm is ___ cm.', answer: 16, type: 'integer' },
  { id: 96, topic: 'RAY OPTICS', text: 'Distance between object and 3x magnified real image is 40 cm. Focal length of mirror is ___ cm.', options: ['-15/2', '-20', '-10', '-15'], answer: 4, type: 'mcq' },
  { id: 97, topic: 'RAY OPTICS', text: 'Ratio of radius of curvature of biconvex lens front and back surfaces is ___', options: ['5:2', '12:5', '5:12', '4:2.5'], answer: 1, type: 'mcq' },
  { id: 98, topic: 'RAY OPTICS', text: 'Magnification of image from biconvex lens formed by two thin planoconvex lenses is:', options: ['-2', '+2.5', '+2', '-2.5'], answer: 1, type: 'mcq', hasDiagram: true },
  { id: 99, topic: 'RAY OPTICS', text: 'Refractive index n of prism where min deviation equals refracting angle satisfies:', options: ['√2 < n < 2√2', 'n ≥ 2', '1 < n < 2', '√2 < n < 2'], answer: 4, type: 'mcq' },
  { id: 100, topic: 'SEMICONDUCTORS', text: 'Combination of inputs A, B, C, D to cause LED to glow is:', options: ['Table 1', 'Table 2', 'Table 3', 'Table 4'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 101, topic: 'SEMICONDUCTORS', text: 'Correct truth table for the given logic gate circuit is:', options: ['Table 1', 'Table 2', 'Table 3', 'Table 4'], answer: 2, type: 'mcq', hasDiagram: true },
  { id: 102, topic: 'SEMICONDUCTORS', text: 'Current through diode D_1 in the given circuit is ___ mA.', answer: 4, type: 'integer', hasDiagram: true },
  { id: 103, topic: 'SEMICONDUCTORS', text: 'Logic function of the given diode circuit is:', options: ['OR Gate', 'NAND Gate', 'NOR Gate', 'AND Gate'], answer: 4, type: 'mcq', hasDiagram: true },
  { id: 104, topic: 'MODERN PHYSICS', text: 'Max kinetic energy of ejected photoelectron from metal of work function 2.8 eV is ___ eV.', options: ['5.1', '6.0', '3.8', '7.8'], answer: 1, type: 'mcq' },
  { id: 105, topic: 'MODERN PHYSICS', text: 'Closest distance of alpha particle from gold nucleus is ___ m.', options: ['2.95 x 10^-14', '3.85 x 10^-16', '2.95 x 10^-16', '3.85 x 10^-14'], answer: 1, type: 'mcq' },
  { id: 106, topic: 'MODERN PHYSICS', text: 'Value of 2πL/h for electron in Bohr orbit with energy -0.04E_o is:', options: ['2', '5', '4', '6'], answer: 3, type: 'mcq' },
  { id: 107, topic: 'MODERN PHYSICS', text: 'Minimum frequency of photon to break particle into 4α particles is ___ kHz.', options: ['9 x 10^19', '9 x 10^20', '14.94 x 10^20', '14.94 x 10^19'], answer: 4, type: 'mcq' },
  { id: 108, topic: 'MODERN PHYSICS', text: 'De Broglie wavelength of oxygen molecule at 27°C is x x 10^-12 m. Value of x is ___', options: ['26', '30', '24', '20'], answer: 1, type: 'mcq' },
  { id: 110, topic: 'MODERN PHYSICS', text: 'Correct order of binding energy for the given nuclear reactions is:', options: ['X₁ > X₂ > X₃', 'X₂ = X₅ = X₃', 'X₁ < X₂ < X₃', 'X₁ < X₅ < X₃'], answer: 1, type: 'mcq' },
  { id: 109, topic: 'MODERN PHYSICS', text: 'Choose correct statement about hydrogen atom spectrum series.', options: ['B, D Only', 'A, B and D Only', 'A, B and C Only', 'A, B Only'], answer: 2, type: 'mcq' },
  { id: 111, topic: 'MODERN PHYSICS', text: 'Ratio of radii R_α/R_β if mass number β = 8α is:', options: ['2', '1', '8', '0.5'], answer: 4, type: 'mcq' }
];
const imageMapping = {
  "1": "page4_img2.jpeg",
  "2": "page4_img3.jpeg",
  "3": "page4_img4.jpeg",
  "4": "page4_img5.jpeg",
  "5": "page4_img7.jpeg",
  "6": "page4_img6.jpeg",
  "7": "page4_img8.jpeg",
  "8": "page4_img9.jpeg",
  "9": "page4_img10.jpeg",
  "10": "page5_img2.jpeg",
  "11": "page5_img3.jpeg",
  "12": "page5_img4.jpeg",
  "13": "page5_img5.jpeg",
  "14": "page5_img6.jpeg",
  "15": "page5_img7.jpeg",
  "16": "page6_img2.jpeg",
  "17": "page6_img3.jpeg",
  "18": "page6_img4.jpeg",
  "19": "page6_img5.jpeg",
  "20": "page7_img6.jpeg",
  "21": "page7_img3.jpeg",
  "22": "page7_img5.jpeg",
  "23": "page7_img7.jpeg",
  "24": "page7_img8.jpeg",
  "25": "page8_img2.jpeg",
  "26": "page8_img3.jpeg",
  "27": "page8_img4.jpeg",
  "28": "page8_img5.jpeg",
  "29": "page8_img6.jpeg",
  "30": "page8_img7.jpeg",
  "31": "page9_img3.jpeg",
  "32": "page9_img4.jpeg",
  "33": "page9_img5.jpeg",
  "34": "page9_img6.jpeg",
  "35": "page9_img7.jpeg",
  "36": "page9_img8.jpeg",
  "37": "page9_img9.jpeg",
  "38": "page9_img10.jpeg",
  "39": "page9_img11.jpeg",
  "40": "page10_img2.jpeg",
  "41": "page10_img3.jpeg",
  "42": "page10_img4.jpeg",
  "43": "page10_img5.jpeg",
  "44": "page10_img6.jpeg",
  "45": "page10_img7.jpeg",
  "46": "page11_img2.jpeg",
  "47": "page11_img3.jpeg",
  "48": "page11_img4.jpeg",
  "49": "page11_img5.jpeg",
  "50": "page11_img6.jpeg",
  "51": "page11_img7.jpeg",
  "52": "page11_img8.jpeg",
  "53": "page12_img5.jpeg",
  "54": "page12_img2.jpeg",
  "55": "page12_img6.jpeg",
  "56": "page12_img4.jpeg",
  "57": "page12_img7.jpeg",
  "58": "page12_img8.jpeg",
  "59": "page12_img9.jpeg",
  "60": "page12_img1.jpeg",
  "61": "page13_img1.jpeg",
  "62": "page13_img3.jpeg",
  "63": "page13_img4.jpeg",
  "64": "page13_img5.jpeg",
  "65": "page13_img6.jpeg",
  "66": "page13_img7.jpeg",
  "67": "page13_img8.jpeg",
  "68": "page14_img2.jpeg",
  "69": "page14_img3.jpeg",
  "70": "page14_img7.jpeg",
  "71": "page14_img5.jpeg",
  "72": "page14_img8.jpeg",
  "73": "page14_img9.jpeg",
  "74": "page14_img10.jpeg",
  "75": "page14_img11.jpeg",
  "76": "page15_img2.jpeg",
  "77": "page15_img3.jpeg",
  "78": "page15_img4.jpeg",
  "79": "page15_img6.jpeg",
  "80": "page15_img7.jpeg",
  "81": "page15_img5.jpeg",
  "82": "page15_img8.jpeg",
  "83": "page16_img4.jpeg",
  "84": "page16_img5.jpeg",
  "85": "page16_img6.jpeg",
  "86": "page16_img7.jpeg",
  "87": "page16_img8.jpeg",
  "88": "page16_img2.jpeg",
  "89": "page16_img9.jpeg",
  "90": "page16_img10.jpeg",
  "91": "page16_img1.jpeg",
  "92": "page17_img2.jpeg",
  "93": "page17_img3.jpeg",
  "94": "page17_img4.jpeg",
  "95": "page17_img5.jpeg",
  "96": "page17_img6.jpeg",
  "97": "page17_img7.jpeg",
  "98": "page17_img8.jpeg",
  "99": "page17_img9.jpeg",
  "100": "page18_img4.jpeg",
  "101": "page18_img5.jpeg",
  "102": "page18_img6.jpeg",
  "103": "page18_img7.jpeg",
  "104": "page19_img3.jpeg",
  "105": "page19_img4.jpeg",
  "106": "page19_img5.jpeg",
  "107": "page19_img6.jpeg",
  "108": "page19_img2.jpeg",
  "109": "page19_img7.jpeg",
  "110": "page19_img8.jpeg",
  "111": "page19_img9.jpeg"
};